# Note that these values are only for fcrepo_wrapper and must match the app
# config in settings.yml, etc. These defaults are primarily for no-argument
# development invocation. See config/fcrepo_wrapper_test.yml for test values.
port: 8984
enable_jms: false
fcrepo_home_dir: tmp/fcrepo4-development-data
verbose: true
# default version: 4.7.3
# version: 4.7.6
validate: false
version_file: ./tmp/fcrepo-webapp-VERSION
instance_dir: ./tmp/
