# reference: https://github.com/mlibrary/heliotrope/blob/master/.rubocop_todo.yml
# Put any overides here
#Lint/AmbiguousBlockAssociation:
#  Exclude:
#    - 'spec/controllers/hyrax/monographs_controller_spec.rb'
#    - 'spec/controllers/roles_controller_spec.rb'

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/LeadingCommentSpace:
  Exclude:
    - 'config/initializers/mailboxer.rb'

Layout/SpaceAroundOperators:
  Exclude:
    - config/application.rb

Layout/SpaceInsideBrackets:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: false

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Lint/RescueException:
  Exclude:
    - 'lib/append_content_service.rb'
    - 'lib/build_content_service.rb'

Metrics/BlockLength:
  Enabled: true
  Max: 295 # default is 25

Metrics/ClassLength:
  # Enabled: true
  # Max: 1000 # default is 100
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'app/controllers/hyrax/data_sets_controller.rb'
    - 'app/jobs/globus_job.rb'
    - 'app/models/collection.rb'
    - 'app/models/data_set.rb'
    - 'app/services/deepblue/yaml_populate_service.rb'
    - 'lib/tasks/curation_concern_report_task.rb'
    - 'lib/tasks/new_content_service2.rb'
    - 'lib/tasks/update_file_derivatives.rake'
    - 'lib/tasks/upgrade_provenance_log.rake'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/controllers/hyrax/data_sets_controller.rb'
    - 'app/helpers/export_files_helper.rb'
    - 'app/helpers/metadata_helper.rb'
    - 'app/helpers/deepblue/export_files_helper.rb'
    - 'app/helpers/deepblue/ingest_helper.rb'
    - 'app/helpers/deepblue/logging_helper.rb'
    - 'app/helpers/deepblue/metadata_helper.rb'
    - 'app/helpers/deepblue/provenance_helper.rb'
    - 'app/jobs/globus_copy_job.rb'
    - 'app/jobs/globus_era.rb'
    - 'app/jobs/globus_job.rb'
    - 'app/jobs/globus_restart_all_job.rb'
    - 'app/models/collection.rb'
    - 'app/models/data_set.rb'
    - 'app/models/file_set.rb'
    - 'app/models/concerns/deepblue/email_behavior.rb'
    - 'app/models/concerns/deepblue/file_set_behavior.rb'
    - 'app/models/concerns/deepblue/metadata_behavior.rb'
    - 'app/models/concerns/deepblue/provenance_behavior.rb'
    - 'app/services/deepblue/log_reader.rb'
    - 'app/services/deepblue/migration_log_reporter.rb'
    - 'app/services/deepblue/yaml_populate_service.rb'
    - 'lib/tasks/active_fedora_indexing_descendent_fetcher2.rb'
    - 'lib/tasks/active_fedora_indexing_reindex_everything2.rb'
    - 'lib/tasks/curation_concerns_report.rake'
    - 'lib/tasks/curation_concern_report_task.rb'
    - 'lib/tasks/extract_files_from_fedora.rake'
    - 'lib/tasks/files_csv_report.rake'
    - 'lib/tasks/new_content_service2.rb'
    - 'lib/tasks/reindex_works_with_mismatching_solr_docs.rake'
    - 'lib/tasks/update_file_derivatives.rake'
    - 'lib/tasks/update_works_total_file_sizes.rake'
    - 'lib/tasks/upgrade_provenance_log.rake'
    - 'lib/tasks/works_and_files_missing_edit_users.rake'
    - 'lib/tasks/works_and_files_missing_solr_docs.rake'
    - 'lib/tasks/works_missing_edit_users.rake'
    - 'lib/tasks/works_missing_solr_docs.rake'
    - 'lib/tasks/works_report.rake'
    - 'lib/tasks/works_with_mismatching_solr_docs.rake'
    - 'spec/models/data_set_spec.rb'

Metrics/ModuleLength:
  Enabled: true
  Max: 1000 # default is 100

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/controllers/hyrax/data_sets_controller.rb'
    - 'app/helpers/export_files_helper.rb'
    - 'app/helpers/metadata_helper.rb'
    - 'app/helpers/deepblue/export_files_helper.rb'
    - 'app/helpers/deepblue/ingest_helper.rb'
    - 'app/helpers/deepblue/logging_helper.rb'
    - 'app/helpers/deepblue/metadata_helper.rb'
    - 'app/helpers/deepblue/provenance_helper.rb'
    - 'app/jobs/globus_copy_job.rb'
    - 'app/jobs/globus_era.rb'
    - 'app/jobs/globus_job.rb'
    - 'app/jobs/globus_restart_all_job.rb'
    - 'app/models/collection.rb'
    - 'app/models/data_set.rb'
    - 'app/models/file_set.rb'
    - 'app/models/concerns/deepblue/email_behavior.rb'
    - 'app/models/concerns/deepblue/file_set_behavior.rb'
    - 'app/models/concerns/deepblue/metadata_behavior.rb'
    - 'app/models/concerns/deepblue/provenance_behavior.rb'
    - 'app/services/deepblue/log_reader.rb'
    - 'app/services/deepblue/migration_log_reporter.rb'
    - 'app/services/deepblue/yaml_populate_service.rb'
    - 'lib/tasks/active_fedora_indexing_descendent_fetcher2.rb'
    - 'lib/tasks/active_fedora_indexing_reindex_everything2.rb'
    - 'lib/tasks/curation_concern_report_task.rb'
    - 'lib/tasks/curation_concerns_report.rake'
    - 'lib/tasks/extract_files_from_fedora.rake'
    - 'lib/tasks/files_csv_report.rake'
    - 'lib/tasks/new_content_service2.rb'
    - 'lib/tasks/reindex_works_with_mismatching_solr_docs.rake'
    - 'lib/tasks/update_file_derivatives.rake'
    - 'lib/tasks/update_works_total_file_sizes.rake'
    - 'lib/tasks/upgrade_provenance_log.rake'
    - 'lib/tasks/works_and_files_missing_edit_users.rake'
    - 'lib/tasks/works_and_files_missing_solr_docs.rake'
    - 'lib/tasks/works_missing_edit_users.rake'
    - 'lib/tasks/works_missing_solr_docs.rake'
    - 'lib/tasks/works_report.rake'
    - 'lib/tasks/works_with_mismatching_solr_docs.rake'
    - 'spec/models/data_set_spec.rb'

Rails/Exit:
  Exclude:
    - 'lib/**/*'

Rails/DynamicFindBy:
  Enabled: false # this seems to recommend changes that cause failures

Rails/Output:
  Exclude:
    - 'config/environments/development.rb'
    - 'lib/tasks/curation_concern_report_task.rb'
    - 'lib/tasks/task_helper.rb'
    - 'lib/tasks/yaml_populate.rb'

#Rails/OutputSafety:
#  Exclude:
#    - 'spec/presenters/concerns/title_presenter_spec.rb'
#    - 'config/initializers/explain_partials.rb'
#    - 'app/services/markdown_service.rb'
#    - 'app/helpers/markdown_helper.rb'
#    - 'app/helpers/gallery_helper.rb'
#    - 'app/renderers/hyrax/renderers/attribute_renderer.rb'
#    - 'app/renderers/hyrax/renderers/markdown_attribute_renderer.rb'

#Rails/SkipsModelValidations:
#  Exclude:
#    - 'spec/jobs/characterize_job_spec.rb'

#RSpec/EmptyExampleGroup:
#  Exclude:
#    - 'spec/actors/hyrax/monograph_actor_spec.rb'

RSpec/EmptyLineAfterFinalLet:
  Enabled: false

RSpec/EmptyLineAfterSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: true
  Max: 103 # default is 5

RSpec/LetSetup:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

#RSpec/SubjectStub:
#  Exclude:
#    - 'spec/models/riiif/file_spec.rb'

RSpec/VerifiedDoubles:
  Enabled: false

Style/Alias:
  Enabled: false

Style/ClassVars:
  Exclude:
    - 'app/jobs/globus_era.rb'
    - 'app/jobs/globus_job.rb'
    - 'app/helpers/deepblue/metadata_helper.rb'
    - 'app/services/deepblue/yaml_populate_service.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'config/initializers/mailboxer.rb'

#Style/GuardClause:
#  Exclude:
#    - 'lib/import/importer.rb'

Style/LineEndConcatenation:
  Exclude:
    - 'lib/tasks/upgrade_provenance_log.rake'

Style/NumericLiterals:
  Exclude:
    - 'config/initializers/mailboxer.rb'

Style/RedundantReturn:
  Enabled: false

Style/RedundantSelf:
  Exclude:
   - 'app/models/concerns/deepblue/metadata_behavior.rb'

#Style/VariableName:
#  Exclude:
#    - app/helpers/metadata_helper.rb

Style/YodaCondition:
  Enabled: false
