 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/job_statuses", type: :request, skip: true do
  
  # JobStatus. As you add validations to JobStatus, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      JobStatus.create! valid_attributes
      get job_statuses_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      job_status = JobStatus.create! valid_attributes
      get job_status_url(job_status)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_job_status_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      job_status = JobStatus.create! valid_attributes
      get edit_job_status_url(job_status)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new JobStatus" do
        expect {
          post job_statuses_url, params: { job_status: valid_attributes }
        }.to change(JobStatus, :count).by(1)
      end

      it "redirects to the created job_status" do
        post job_statuses_url, params: { job_status: valid_attributes }
        expect(response).to redirect_to(job_status_url(JobStatus.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new JobStatus" do
        expect {
          post job_statuses_url, params: { job_status: invalid_attributes }
        }.to change(JobStatus, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post job_statuses_url, params: { job_status: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested job_status" do
        job_status = JobStatus.create! valid_attributes
        patch job_status_url(job_status), params: { job_status: new_attributes }
        job_status.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the job_status" do
        job_status = JobStatus.create! valid_attributes
        patch job_status_url(job_status), params: { job_status: new_attributes }
        job_status.reload
        expect(response).to redirect_to(job_status_url(job_status))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        job_status = JobStatus.create! valid_attributes
        patch job_status_url(job_status), params: { job_status: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested job_status" do
      job_status = JobStatus.create! valid_attributes
      expect {
        delete job_status_url(job_status)
      }.to change(JobStatus, :count).by(-1)
    end

    it "redirects to the job_statuses list" do
      job_status = JobStatus.create! valid_attributes
      delete job_status_url(job_status)
      expect(response).to redirect_to(job_statuses_url)
    end
  end
end
