# AWS S3 APTrust KEYS [for preview]

# Config for apt_upload and apt_download
DownloadDir: Settings.APTrustRestore
AptrustApiUser: "fritx@umich.edu"
#AptrustApiUrl: "https://repo.aptrust.org/member-api/v3/"
AptrustApiUrl: "https://demo.aptrust.org/member-api/v3/"
AptrustApiKey: "8f449ae1cae5b54329b1bdc75296567b"
#
Bucket: 'aptrust.receiving.test.umich.edu'
BucketRegion: "us-east-1"
AwsAccessKeyId: AKIA6QO2K7LITSQRFB7A
AwsSecretAccessKey: "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"
