# data/scheduler_jobs.yml
# server: testing
# last updated: 2022/07/18

about_to_deactivate_embargoes_job:
  # Run once a day, fifteen minutes after midnight (which is offset by 4 or [5 during daylight savings time], due to GMT)
  #      M  H
  cron: '15 4 * * *'
  # rails_env: production
  class: AboutToExpireEmbargoesJob
  queue: scheduler
  description: About to deactivate embargoes job.
  args:
    email_owner: true
    hostnames:
      - 'deepblue.lib.umich.edu'
      - 'testing.deepblue.lib.umich.edu'
    test_mode: false
    verbose: true

about_to_deactivate_embargoes_at_2_days_job:
  # Run once a day, twenty minutes after midnight (which is offset by 4 or [5 during daylight savings time], due to GMT)
  #      M  H
  cron: '20 4 * * *'
  # rails_env: production
  class: AboutToExpireEmbargoesJob
  queue: scheduler
  description: About to deactivate embargoes job.
  args:
    x_by_request_only: true
    email_owner: true
    expiration_lead_days: 2
    test_mode: false
    hostnames:
      - 'testing.deepblue.lib.umich.edu'
    verbose: true

deactivate_expired_embargoes_job:
  # Run once a day, five minutes after midnight (which is offset by 4 or [5 during daylight savings time], due to GMT)
  #      M H
  cron: '5 4 * * *'
  # rails_env: production
  class: DeactivateExpiredEmbargoesJob
  queue: scheduler
  description: Deactivate embargoes job.
  args:
    email_owner: true
    hostnames:
      - 'deepblue.lib.umich.edu'
      - 'testing.deepblue.lib.umich.edu'
    test_mode: false
    verbose: true

clean_derivatives_dir_job:
  # Run once a week on Sundays at 4:05 PM (which is offset by 4 or [5 during daylight savings time], due to GMT)
  #      M  H     DoW
  cron: '5 21 * * 0'
  # rails_env: production
  class: CleanDerivativesDirJob
  queue: scheduler
  description: Clean the tmp/derivatives directory.
  args:
    days_old: 7
    email_results_to:
      - 'fritx@umich.edu'
    hostnames:
      - 'deepblue.lib.umich.edu'
      - 'testing.deepblue.lib.umich.edu'
    verbose: true
    subscription_service_id: clean_derivatives_dir_job

clean_search:
  # Run once a day, 36 minutes after midnight (which is offset by 4 or [5 during daylight savings time], due to GMT)
  #       M H D
  cron: '36 4 * * *'
  class: RakeTaskJob
  queue: scheduler
  description: Run rake blacklight:delete_old_searches
  args:
    hostnames:
      - 'deepblue.lib.umich.edu'
      - 'staging.deepblue.lib.umich.edu'
      - 'testing.deepblue.lib.umich.edu'
    job_delay: 0
    rake_task: 'blacklight:delete_old_searches[30]'
    subscription_service_id: clean_search
    verbose: true

clean_tmp:
  # Run once a week on Saturday, 6 minutes after midnight (which is offset by 4 or [5 during daylight savings time], due to GMT)
  #       M H D
  cron: '6 4 * * 6'
  class: RakeTaskJob
  queue: scheduler
  description: Run rake tmp:clean (Saturdays)
  args:
    hostnames:
      - 'deepblue.lib.umich.edu'
      - 'staging.deepblue.lib.umich.edu'
      - 'testing.deepblue.lib.umich.edu'
    job_delay: 0
    rake_task: 'tmp:clean'
    subscription_service_id: clean_tmp
    verbose: true

clean_tmp2:
  # Run once daily at 6 minutes after noon (which is offset by 4 or [5 during daylight savings time], due to GMT)
  #       M H D
  cron: '6 17 * * *'
  class: RakeTaskJob
  queue: scheduler
  description: Run rake tmp:clean (daily on testing)
  args:
    by_request_only: true
    hostnames:
      - 'testing.deepblue.lib.umich.edu'
    job_delay: 0
    rake_task: 'tmp:clean'
    verbose: true

doi_pending_report_job:
  # Run once on Saturdays at two am (which is offset by 4 or [5 during daylight savings time], due to GMT)
  #      M H D
  cron: '0 6 * * 6'
  class: DoiPendingReportJob
  queue: scheduler
  description: DOI pending report job.
  args:
    by_request_only: true
    hostnames:
      - 'deepblue.lib.umich.edu'
      - 'staging.deepblue.lib.umich.edu'
      - 'testing.deepblue.lib.umich.edu'
    quiet: true
    subscription_service_id: doi_pending_report_job
    user_email:
      - 'fritx@umich.edu'

find_and_fix_job:
  # Run once a day, 15 minutes after midnight (which is offset by 4 or [5 during daylight savings time], due to GMT)
  #       M H D
  cron: '15 5 * * *'
  class: FindAndFixJob
  queue: scheduler
  description: Find and fix problems
  args:
    filter_date_begin: now - 7 days
    filter_date_end: now
    hostnames:
      - 'deepblue.lib.umich.edu'
      - 'staging.deepblue.lib.umich.edu'
      - 'testing.deepblue.lib.umich.edu'
    subscription_service_id: find_and_fix_job
    verbose: false

find_and_fix_job_all:
  # Run once a day, 15 minutes after midnight (which is offset by 4 or [5 during daylight savings time], due to GMT)
  #       M H D
  cron: '15 4 * * *'
  class: FindAndFixJob
  queue: scheduler
  description: Find and fix problems
  args:
    by_request_only: true
    hostnames:
      - 'block.deepblue.lib.umich.edu'
      - 'block.testing.deepblue.lib.umich.edu'
    subscription_service_id: find_and_fix_job_all
    verbose: false

globus_errors_report_job:
  # Run once a day, 5 minutes after six pm (which is offset by 4 or [5 during daylight savings time], due to GMT)
  #      M H D
  cron: '5 18 * * *'
  class: GlobusErrorsReportJob
  queue: scheduler
  description: Globus error report job.
  args:
    hostnames:
      - 'deepblue.lib.umich.edu'
      - 'staging.deepblue.lib.umich.edu'
      - 'testing.deepblue.lib.umich.edu'
    quiet: true
    subscription_service_id: globus_errors_report_job

globus_status_report_job:
  # Run once a day, 5 minutes after six pm (which is offset by 4 or [5 during daylight savings time], due to GMT)
  #      M H D
  cron: '5 18 * * *'
  class: GlobusStatusReportJob
  queue: scheduler
  description: Globus status report job.
  args:
    hostnames:
      - 'deepblue.lib.umich.edu'
      - 'staging.deepblue.lib.umich.edu'
      - 'testing.deepblue.lib.umich.edu'
    quiet: true
    subscription_service_id: globus_status_report_job

heartbeat_email_job:
  # Run once a day, one minute after midnight (which is offset by 4 or [5 during daylight savings time], due to GMT)
  #      M H
  # cron: '*/5 * * * *'
  cron: '1 5 * * *'
  # rails_env: production
  class: HeartbeatEmailJob
  queue: scheduler
  description: Heartbeat email job.
  args:
    hostnames:
      - 'deepblue.lib.umich.edu'
      - 'testing.deepblue.lib.umich.edu'
    subscription_service_id: heartbeat_email_job

monthly_events_report_job:
  # Run once a month on the 1st, twenty-five minutes after midnight (which is offset by 4 or [5 during daylight savings time], due to GMT)
  #      M H D
  # cron: '*/5 * * * *'
  cron: '25 4 1 * *'
  class: MonthlyEventsReportJob
  queue: scheduler
  description: Monthly events report job.
  args:
    hostnames:
      - 'deepblue.lib.umich.edu'
      - 'staging.deepblue.lib.umich.edu'
      - 'testing.deepblue.lib.umich.edu'
    quiet: true
    this_month: false

reset_condensed_events_job:
  # Run on demand
  #      M H D
  # cron: '*/5 * * * *'
  cron: '25 5 * * *'
  class: ResetCondensedEventsJob
  queue: scheduler
  description: Reset the condensed events job.
  args:
    hostnames:
      - 'deepblue.lib.umich.edu'
      - 'staging.deepblue.lib.umich.edu'
      - 'testing.deepblue.lib.umich.edu'
    quiet: true
    by_request_only: true
    subscription_service_id: reset_condensed_events_job

resolrize_job:
  # Run on demand
  #      M H D
  # cron: '*/5 * * * *'
  cron: '25 5 * * *'
  class: ResolrizeJob
  queue: scheduler
  description: Reindex everything in solr.
  args:
    hostnames:
      - 'deepblue.lib.umich.edu'
      - 'staging.deepblue.lib.umich.edu'
      - 'testing.deepblue.lib.umich.edu'
    quiet: true
    by_request_only: true
    subscription_service_id: resolrize_job

sitemap_generator_job:
  # Run once a week at midnight
  #      M H D
  # cron: '*/5 * * * *'
  cron: '0 5 * * 0'
  # cron: '10 * * * *'
  class: SitemapGeneratorJob
  queue: default
  description: Sitemap generator job.
  args:
    hostnames:
      - 'deepblue.lib.umich.edu'
      - 'staging.deepblue.lib.umich.edu'
      - 'testing.deepblue.lib.umich.edu'
    verbose: true

update_condensed_events_job_daily:
  # Run once a day, twenty-five minutes after midnight (which is offset by 4 or [5 during daylight savings time], due to GMT)
  #      M H D
  # cron: '*/5 * * * *'
  cron: '25 4 * * *'
  class: UpdateCondensedEventsJob
  queue: scheduler
  description: Update the condensed events job.
  args:
    hostnames:
      - 'deepblue.lib.umich.edu'
      - 'staging.deepblue.lib.umich.edu'
      - 'testing.deepblue.lib.umich.edu'
    quiet: true

user_stat_importer_job:
  # Run once a day, thirty minutes after midnight (which is offset by 4 or [5 during daylight savings time], due to GMT)
  #      M  H
  cron: '30 4 * * *'
  # rails_env: production
  class: UserStatImporterJob
  queue: scheduler
  description: Import user stats job.
  args:
    hostnames:
      - 'deepblue.lib.umich.edu'
    verbose: false
    test: false

works_report_job_daily:
  # Run once a day, five minutes after midnight (which is offset by 4 or [5 during daylight savings time], due to GMT)
  #      M H D
  cron: '5 4 * * *'
  class: WorksReportJob
  queue: scheduler
  description: Daily Works report job.
  args:
    by_request_only: true
    hostnames:
      - 'x.testing.deepblue.lib.umich.edu'
    quiet: true
    report_file_prefix: '%date%.%hostname%.works_report'
    report_dir: '/deepbluedata-dataden/download-prep/reports'
    subscription_service_id: works_report_job_daily

works_report_job_monthly:
  # Run once a month on the 1st, five minutes after midnight (which is offset by 4 or [5 during daylight savings time], due to GMT)
  #      M H D
  # cron: '*/5 * * * *'
  cron: '5 4 1 * *'
  class: WorksReportJob
  queue: scheduler
  description: Monthly Works report job.
  args:
    hostnames:
      - 'deepblue.lib.umich.edu'
      - 'staging.deepblue.lib.umich.edu'
      - 'testing.deepblue.lib.umich.edu'
    quiet: true
    report_file_prefix: '%date%.%hostname%.works_report'
    report_dir: '/deepbluedata-dataden/download-prep/reports'
    subscription_service_id: works_report_job_monthly
